---
#file: rules/nso/tasks/nso_add_devices.yml

- name: fetch master hostkey
  shell: ssh-keyscan -4 -T 5 -t rsa {{groups['master'][0]}}   2>/dev/null | awk '{ print $3; }' > /tmp/key.txt

- name: assign hostkey to local variable catkey
  shell: cat /tmp/key.txt
  register: catkey

- name: copy device xml and inventory xml files 
  vars:
   host_key: "{{catkey.stdout}}"

  template:
    src: "{{ item }}.j2"
    dest: '{{ansible_env.HOME}}/{{item}}.xml'
  with_items:
    - device
    - inventory

- name: load merge device and invetory files
  shell: "source {{ nso_install_path }}/ncsrc;{{ nso_install_path }}/bin/ncs  --mergexmlfiles {{ansible_env.HOME}}/{{item}}.xml --cd {{ansible_env.HOME}}/ncs-run"
  with_items:
    - device
    - inventory

- name: nso sync device master
  shell: "source {{ nso_install_path }}/ncsrc; sh {{ansible_env.HOME}}/scripts/sync-device.sh master"